---
EnableDefaultLinters: true
exclude:
  - '**/vendor/**/*'
  - '**/node_modules/**/*'
  - 'lib/jumpstart/app/views/jumpstart/docs/**'
linters:
  ErbSafety:
    enabled: true
  Rubocop:
    enabled: false
