--- !ruby/object:Jumpstart::Configuration
application_name: WorkDonePerfect
business_name: WorkDonePerfect, LLC
domain: workdoneperfect.com
support_email: jack@workdoneperfect.com
default_from_email: jack@workdoneperfect.com
business_address: |-
  3850 N Mississippi Ave #A103
  Portland, OR 97227
background_job_processor: sidekiq
email_provider: ''
personal_accounts: true
solargraph: false
register_with_account: false
apns: false
fcm: false
collect_billing_address: false
