--- !ruby/object:Jumpstart::Configuration
application_name: Litehouse
business_name: Litehouse Company, LLC
domain: example.com
support_email: support@lighthouse.com
default_from_email: Jumpstart <support@example.com>
business_address: |-
  3850 N Mississippi Ave #A103
  Portland, OR 97227
background_job_processor: async
email_provider: ''
personal_accounts: true
solargraph: false
register_with_account: false
apns: false
fcm: false
collect_billing_address: false
